'use client';

import React, { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { api, Document, CaseBrief as CaseBriefType, CaseComparison } from '@/lib/api';
import { 
  FileText, 
  Loader2, 
  Scale, 
  Download, 
  Eye,
  CheckCircle2,
  XCircle,
  BookOpen,
  Gavel,
  Users,
  Calendar,
  AlertCircle,
  FileCheck,
  GitCompare,
  Sparkles,
  ChevronDown,
  ChevronUp,
  Copy,
  Check
} from 'lucide-react';

export default function CaseBrief() {
  const { session } = useAuth();
  const [documents, setDocuments] = useState<Document[]>([]);
  const [selectedDocumentId, setSelectedDocumentId] = useState<string>('');
  const [briefType, setBriefType] = useState<'full' | 'summary'>('full');
  const [isLoading, setIsLoading] = useState(false);
  const [caseBrief, setCaseBrief] = useState<CaseBriefType | null>(null);
  const [error, setError] = useState<string>('');
  const [loadingDocuments, setLoadingDocuments] = useState(true);
  
  // Comparison feature
  const [compareMode, setCompareMode] = useState(false);
  const [selectedDocuments, setSelectedDocuments] = useState<string[]>([]);
  const [comparison, setComparison] = useState<CaseComparison | null>(null);
  const [comparisonFocus, setComparisonFocus] = useState<string>('');

  useEffect(() => {
    if (session?.access_token) {
      loadDocuments();
    }
  }, [session]);

  const loadDocuments = async () => {
    if (!session?.access_token) return;
    
    try {
      setLoadingDocuments(true);
      const docs = await api.getDocuments(session.access_token);
      setDocuments(docs);
    } catch (err: any) {
      console.error('Failed to load documents:', err);
      setError('Failed to load documents');
    } finally {
      setLoadingDocuments(false);
    }
  };

  const handleGenerateBrief = async () => {
    if (!selectedDocumentId || !session?.access_token) return;

    setIsLoading(true);
    setError('');
    setCaseBrief(null);

    try {
      console.log('Generating case brief for document:', selectedDocumentId);
      
      const brief = await api.generateCaseBrief(
        selectedDocumentId,
        session.access_token,
        { brief_type: briefType }
      );

      console.log('Case brief generated:', brief);
      setCaseBrief(brief);
    } catch (err: any) {
      console.error('Failed to generate case brief:', err);
      setError(err.message || 'Failed to generate case brief');
    } finally {
      setIsLoading(false);
    }
  };

  const handleCompareCases = async () => {
    if (selectedDocuments.length < 2 || !session?.access_token) return;

    setIsLoading(true);
    setError('');
    setComparison(null);

    try {
      console.log('Comparing cases:', selectedDocuments);
      
      const result = await api.compareCases(
        selectedDocuments,
        session.access_token,
        { comparison_focus: comparisonFocus || undefined }
      );

      console.log('Comparison generated:', result);
      setComparison(result);
    } catch (err: any) {
      console.error('Failed to compare cases:', err);
      setError(err.message || 'Failed to compare cases');
    } finally {
      setIsLoading(false);
    }
  };

  const toggleDocumentSelection = (docId: string) => {
    setSelectedDocuments(prev => 
      prev.includes(docId) 
        ? prev.filter(id => id !== docId)
        : [...prev, docId]
    );
  };

  const handleDownloadBrief = () => {
    if (!caseBrief) return;

    const content = `${caseBrief.case_name || 'Case Brief'}\n\n${caseBrief.brief_content}\n\n---\nGenerated by LexAI Scholar\n${new Date(caseBrief.metadata.generated_at).toLocaleString()}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${caseBrief.case_name || 'case-brief'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopyToClipboard = async () => {
    if (!caseBrief) return;
    
    try {
      await navigator.clipboard.writeText(caseBrief.brief_content);
      // Could add a toast notification here
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-lg p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-purple-500/20 p-3 rounded-lg">
            <Scale className="w-6 h-6 text-purple-400" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white">Case Brief Generator</h2>
            <p className="text-gray-400 text-sm">
              Generate structured legal case briefs from your uploaded documents
            </p>
          </div>
        </div>

        {/* Mode Toggle */}
        <div className="flex gap-2 mb-4">
          <button
            onClick={() => { setCompareMode(false); setCaseBrief(null); setComparison(null); }}
            className={`flex-1 py-2 px-4 rounded-lg font-medium transition ${
              !compareMode 
                ? 'bg-purple-600 text-white' 
                : 'bg-slate-700 text-gray-300 hover:bg-slate-600'
            }`}
          >
            <FileCheck className="w-4 h-4 inline mr-2" />
            Single Brief
          </button>
          <button
            onClick={() => { setCompareMode(true); setCaseBrief(null); setComparison(null); }}
            className={`flex-1 py-2 px-4 rounded-lg font-medium transition ${
              compareMode 
                ? 'bg-purple-600 text-white' 
                : 'bg-slate-700 text-gray-300 hover:bg-slate-600'
            }`}
          >
            <GitCompare className="w-4 h-4 inline mr-2" />
            Compare Cases
          </button>
        </div>

        {!compareMode ? (
          // Single Brief Mode
          <div className="space-y-4">
            {/* Document Selection */}
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Select Document
              </label>
              {loadingDocuments ? (
                <div className="flex items-center gap-2 text-gray-400">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span className="text-sm">Loading documents...</span>
                </div>
              ) : documents.length === 0 ? (
                <div className="text-gray-400 text-sm">
                  No documents available. Please upload a legal case document first.
                </div>
              ) : (
                <select
                  value={selectedDocumentId}
                  onChange={(e) => setSelectedDocumentId(e.target.value)}
                  className="w-full bg-slate-700 border border-slate-600 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-purple-500"
                >
                  <option value="">-- Select a document --</option>
                  {documents.map(doc => (
                    <option key={doc.id} value={doc.id}>
                      {doc.filename} {doc.title ? `- ${doc.title}` : ''}
                    </option>
                  ))}
                </select>
              )}
            </div>

            {/* Brief Type */}
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Brief Type
              </label>
              <div className="flex gap-3">
                <button
                  onClick={() => setBriefType('full')}
                  className={`flex-1 py-2 px-4 rounded-lg font-medium transition ${
                    briefType === 'full'
                      ? 'bg-purple-600 text-white'
                      : 'bg-slate-700 text-gray-300 hover:bg-slate-600'
                  }`}
                >
                  <BookOpen className="w-4 h-4 inline mr-2" />
                  Full Brief
                </button>
                <button
                  onClick={() => setBriefType('summary')}
                  className={`flex-1 py-2 px-4 rounded-lg font-medium transition ${
                    briefType === 'summary'
                      ? 'bg-purple-600 text-white'
                      : 'bg-slate-700 text-gray-300 hover:bg-slate-600'
                  }`}
                >
                  <Sparkles className="w-4 h-4 inline mr-2" />
                  Quick Summary
                </button>
              </div>
              <p className="text-xs text-gray-400 mt-2">
                {briefType === 'full' 
                  ? 'Comprehensive brief with all sections (Facts, Issues, Holding, Reasoning, etc.)'
                  : 'Concise 2-3 paragraph summary of the case'
                }
              </p>
            </div>

            {/* Generate Button */}
            <button
              onClick={handleGenerateBrief}
              disabled={!selectedDocumentId || isLoading}
              className="w-full bg-purple-600 hover:bg-purple-700 disabled:bg-slate-600 disabled:cursor-not-allowed text-white py-3 rounded-lg font-medium transition flex items-center justify-center gap-2"
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  <span>Generating Case Brief...</span>
                </>
              ) : (
                <>
                  <Gavel className="w-5 h-5" />
                  <span>Generate Case Brief</span>
                </>
              )}
            </button>
          </div>
        ) : (
          // Comparison Mode
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Select Documents to Compare (2+)
              </label>
              {loadingDocuments ? (
                <div className="flex items-center gap-2 text-gray-400">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span className="text-sm">Loading documents...</span>
                </div>
              ) : documents.length < 2 ? (
                <div className="text-gray-400 text-sm">
                  You need at least 2 documents to compare cases.
                </div>
              ) : (
                <div className="space-y-2 max-h-48 overflow-y-auto">
                  {documents.map(doc => (
                    <label
                      key={doc.id}
                      className="flex items-center gap-3 p-3 bg-slate-700 hover:bg-slate-600 rounded-lg cursor-pointer transition"
                    >
                      <input
                        type="checkbox"
                        checked={selectedDocuments.includes(doc.id)}
                        onChange={() => toggleDocumentSelection(doc.id)}
                        className="w-4 h-4 text-purple-600"
                      />
                      <div className="flex-1">
                        <div className="text-white text-sm font-medium">{doc.filename}</div>
                        {doc.title && (
                          <div className="text-gray-400 text-xs">{doc.title}</div>
                        )}
                      </div>
                    </label>
                  ))}
                </div>
              )}
            </div>

            {/* Comparison Focus (Optional) */}
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Focus Area (Optional)
              </label>
              <input
                type="text"
                value={comparisonFocus}
                onChange={(e) => setComparisonFocus(e.target.value)}
                placeholder="e.g., holdings, reasoning, procedural history"
                className="w-full bg-slate-700 border border-slate-600 rounded-lg px-4 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-purple-500"
              />
              <p className="text-xs text-gray-400 mt-1">
                Specify what aspect to focus on in the comparison
              </p>
            </div>

            {/* Compare Button */}
            <button
              onClick={handleCompareCases}
              disabled={selectedDocuments.length < 2 || isLoading}
              className="w-full bg-purple-600 hover:bg-purple-700 disabled:bg-slate-600 disabled:cursor-not-allowed text-white py-3 rounded-lg font-medium transition flex items-center justify-center gap-2"
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  <span>Comparing Cases...</span>
                </>
              ) : (
                <>
                  <GitCompare className="w-5 h-5" />
                  <span>Compare Cases ({selectedDocuments.length} selected)</span>
                </>
              )}
            </button>
          </div>
        )}

        {/* Error Display */}
        {error && (
          <div className="mt-4 bg-red-500/10 border border-red-500/30 rounded-lg p-3 flex items-start gap-2">
            <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
            <div className="text-red-300 text-sm">{error}</div>
          </div>
        )}
      </div>

      {/* Case Brief Display */}
      {caseBrief && !compareMode && (
        <CaseBriefDisplay 
          brief={caseBrief}
          onDownload={handleDownloadBrief}
          onCopy={handleCopyToClipboard}
        />
      )}

      {/* Comparison Display */}
      {comparison && compareMode && (
        <ComparisonDisplay comparison={comparison} />
      )}
    </div>
  );
}

interface CaseBriefDisplayProps {
  brief: CaseBriefType;
  onDownload: () => void;
  onCopy: () => void;
}

function CaseBriefDisplay({ brief, onDownload, onCopy }: CaseBriefDisplayProps) {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['all']));
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    onCopy();
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const toggleSection = (section: string) => {
    setExpandedSections(prev => {
      const next = new Set(prev);
      if (next.has(section)) {
        next.delete(section);
      } else {
        next.add(section);
      }
      return next;
    });
  };

  return (
    <div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-lg overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600/20 to-blue-600/20 border-b border-slate-700 p-6">
        <div className="flex items-start justify-between gap-4">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <Gavel className="w-5 h-5 text-purple-400" />
              <h3 className="text-xl font-bold text-white">
                {brief.case_name || 'Case Brief'}
              </h3>
            </div>
            <div className="flex flex-wrap gap-4 text-sm text-gray-300">
              <div className="flex items-center gap-1">
                <FileText className="w-4 h-4 text-gray-400" />
                <span>{brief.brief_type === 'full' ? 'Full Brief' : 'Summary'}</span>
              </div>
              <div className="flex items-center gap-1">
                <Calendar className="w-4 h-4 text-gray-400" />
                <span>{new Date(brief.metadata.generated_at).toLocaleDateString()}</span>
              </div>
              <div className="flex items-center gap-1">
                <Sparkles className="w-4 h-4 text-gray-400" />
                <span>{brief.metadata.usage.total_tokens} tokens</span>
              </div>
            </div>
          </div>
          
          {/* Actions */}
          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="p-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition"
              title="Copy to clipboard"
            >
              {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
            </button>
            <button
              onClick={onDownload}
              className="p-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition"
              title="Download brief"
            >
              <Download className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        {brief.brief_type === 'full' && Object.keys(brief.sections).length > 0 ? (
          // Structured sections view
          <div className="space-y-4">
            {Object.entries(brief.sections).map(([key, content]) => (
              <div key={key} className="border border-slate-600 rounded-lg overflow-hidden">
                <button
                  onClick={() => toggleSection(key)}
                  className="w-full flex items-center justify-between p-4 bg-slate-700/50 hover:bg-slate-700 transition"
                >
                  <span className="text-white font-semibold capitalize">
                    {key.replace(/_/g, ' ')}
                  </span>
                  {expandedSections.has(key) ? (
                    <ChevronUp className="w-4 h-4 text-gray-400" />
                  ) : (
                    <ChevronDown className="w-4 h-4 text-gray-400" />
                  )}
                </button>
                {expandedSections.has(key) && (
                  <div className="p-4 bg-slate-800/30">
                    <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">
                      {content}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        ) : (
          // Plain text view
          <div className="prose prose-invert max-w-none">
            <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">
              {brief.brief_content}
            </div>
          </div>
        )}

        {/* Metadata Footer */}
        <div className="mt-6 pt-4 border-t border-slate-700">
          <div className="grid grid-cols-3 gap-4 text-xs text-gray-400">
            <div>
              <div className="font-semibold text-gray-300 mb-1">Model</div>
              <div>{brief.metadata.model}</div>
            </div>
            <div>
              <div className="font-semibold text-gray-300 mb-1">Chunks Analyzed</div>
              <div>{brief.metadata.chunks_processed}</div>
            </div>
            <div>
              <div className="font-semibold text-gray-300 mb-1">Characters</div>
              <div>{brief.metadata.character_count.toLocaleString()}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

interface ComparisonDisplayProps {
  comparison: CaseComparison;
}

function ComparisonDisplay({ comparison }: ComparisonDisplayProps) {
  return (
    <div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-lg overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600/20 to-purple-600/20 border-b border-slate-700 p-6">
        <div className="flex items-center gap-3 mb-3">
          <GitCompare className="w-6 h-6 text-blue-400" />
          <h3 className="text-xl font-bold text-white">Case Comparison Analysis</h3>
        </div>
        <div className="flex flex-wrap gap-2">
          {comparison.case_names.map((name, idx) => (
            <span key={idx} className="px-3 py-1 bg-slate-700 rounded-full text-sm text-gray-300">
              {name}
            </span>
          ))}
        </div>
        <div className="mt-3 text-sm text-gray-400">
          Comparing {comparison.cases_compared} cases • Generated on {new Date(comparison.generated_at).toLocaleDateString()}
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        <div className="prose prose-invert max-w-none">
          <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">
            {comparison.comparison}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-6 pt-4 border-t border-slate-700">
          <div className="text-xs text-gray-400">
            <span className="font-semibold text-gray-300">Tokens used:</span> {comparison.usage.total_tokens}
          </div>
        </div>
      </div>
    </div>
  );
}

